/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_martijncourteaux_multitouchgestures_EventDispatch */

#ifndef _Included_com_martijncourteaux_multitouchgestures_EventDispatch
#define _Included_com_martijncourteaux_multitouchgestures_EventDispatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_martijncourteaux_multitouchgestures_EventDispatch
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_martijncourteaux_multitouchgestures_EventDispatch_init
  (JNIEnv *, jclass);

/*
 * Class:     com_martijncourteaux_multitouchgestures_EventDispatch
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_martijncourteaux_multitouchgestures_EventDispatch_start
  (JNIEnv *, jclass);

/*
 * Class:     com_martijncourteaux_multitouchgestures_EventDispatch
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_martijncourteaux_multitouchgestures_EventDispatch_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
